spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/TTJ-online-davomat"
    username: "JavaDbUser"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-message: always
  port: 8081
